### PR TITLE
Regenerated bindings.

### PR DESCRIPTION
**Pull request by eaplatanios**
TF commit d1db9860a24af2ce64626fe4c3bee69f83700afa.

### CODE REVIEW

**Comment by rxwei** [comment]
Could you please include which TF commit you generated bindings against in the PR description?

**Comment by eaplatanios** [comment]
Sorry I just added that in the description.

**Comment by rxwei** [comment]
When I merge this, could you start a PR to update https://github.com/apple/swift/blob/tensorflow/utils/update_checkout/update-checkout-config.json as well?

**Comment by eaplatanios** [comment]
Done [here](https://github.com/apple/swift/pull/24017).

**Pull request merged**
