### PR TITLE
Omit the "values" label

### PR DESCRIPTION
**Pull request by rxwei**
The "values" label is used in most collection ops, and is useless.

Before:
```swift
Raw.concatV2(values:axis:)
Raw.pack(values:)
```

After:
```swift
Raw.concatV2(_:axis:)
Raw.pack(_:)
```

### CODE REVIEW

**Comment by rxwei** [comment]
My local tensorflow installation doesn't work well with `generate-wrappers.py` for some reason

```console
Traceback (most recent call last):
  File "generate_wrappers.py", line 475, in <module>
    tf.app.run(main)
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "generate_wrappers.py", line 431, in main
    api_def_map = c_api_util.ApiDefMap()
AttributeError: 'module' object has no attribute 'ApiDefMap'
```

**Comment by LaurentMazare** [comment]
Could you check your local tensorflow version ? I think that the ApiDefMap python wrapper was only introduced in 1.9 and the current bindings were generated for 1.9.0rc1 (you can check this at the beginning of RawOpsGenerated.py)

**Comment by rxwei** [comment]
Ah ok, mine was 1.8 :)

**Comment by LaurentMazare** [comment]
Do you want to regenerate the bindings with the latest version ? Otherwise we can first merge your change and I'll regenerate `RawOpsGenerated.swift` and push it on my side.
Also we don't have a good story on how the compiler repo is synchronised with this so we will have to push the stdlib changes simultaneously (as `Raw.pack` is used in `Tensor.swift` for example).

**Comment by rxwei** [comment]
I can generate it. Still waiting for the TF 1.9 package to build :)

Not sure how to track those either. I'll update the stdlib side once this PR is in.

**Comment by LaurentMazare** [comment]
Perfect thanks, also feel free to add a note to `README.md` to make it explicit that we require TF 1.9 (otherwise I will add it once you've pushed your changes).

**Comment by rxwei** [comment]
Done!

**Comment by LaurentMazare** [comment]
Note that your generated `RawOpsGenerated.swift` file did not include the documentation/comments probably because you didn't use the `--api_def_path` flag when generating it. Also it was for 1.9.0rc0 rather than 1.9.0rc1 so I regenerated it and pushed the change.

**Comment by rxwei** [comment]
Sorry about that!

**Pull request merged**
